### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by datatalking** [PacktPublishing/Hands-on-Application-Development-with-PyCharm#13]

**Comment by packt-pradeeps** [comment]
Yes

**Comment by datatalking** [comment]
So all of the functions in the book haven't had any issues despite over a dozen updates and changes with PyCharm since 2019?

**Comment by packt-pradeeps** [comment]
The examples should work fine unless something has been deprecated. Please let us know if you find anything not working.

**Comment by datatalking** [comment]
If/when I submit a PR for any depreciations or errata you will add me as a repo contributor?
